version: '3'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    container_name: santri_db
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: santri_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    volumes:
      - ./database/data/:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d/
  web:
    image: nginx:latest
    restart: on-failure
    container_name: santri_web
    ports:
     - "9000:80"
    volumes:
        - ./app:/application     
        - ./site.conf:/etc/nginx/conf.d/default.conf   
    links:
      - app
  app:
    build: ./app/    
    container_name: santri_app
    restart: on-failure
    environment:
      DEBUG: 'true'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: santri_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./app:/application      
    links:
      - db